server:
  servlet.context-path: /api/v1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authdb
    username: root
    password: ${database.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

s3:
  bucket: "auth-service-store"
  key: "credentials_{0}.properties"
#  hibernate:
#    c3p0:
#      min_size: 5
#      max_size: 20
#      timeout: 300
#      max_statements: 50
#      idle_test_period: 3000